apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-btpcfgbs
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/python-btpcfgbs:2b1402d64160a000d3939fc24cc1569558d58d59@sha256:82dc4893e6b3de33f5882fea5281358496bbb349026c0f3df0c72595c56c3562
        name: container-image  
